# A5: Optimization Human Preference & LLM-as-a-Judge
**Course:** AT82.05 Artificial Intelligence: Natural Language Understanding (NLU)  
**Student:** *st125982*  

This notebook implements the full assignment pipeline:

1. Dataset preparation with `jondurbin/truthy-dpo-v0.1`
2. DPO training with `trl.DPOTrainer`
3. Saving and pushing the aligned model to Hugging Face Hub
4. LLM-as-a-Judge evaluation on AlpacaEval (`helpful_base`)

In [20]:
# Core libraries
import os
import re
import json
import random
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
from datasets import load_dataset
from huggingface_hub import login
from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed, pipeline, logging as hf_logging, TrainerCallback

# Compatibility shim for TRL 0.28 with some Transformers builds
import transformers.utils as _tf_utils
if not hasattr(_tf_utils, "is_rich_available"):
    def _is_rich_available():
        try:
            import rich  # noqa: F401
            return True
        except Exception:
            return False

    _tf_utils.is_rich_available = _is_rich_available

from trl import DPOTrainer, DPOConfig

warnings.filterwarnings("ignore")
hf_logging.set_verbosity_error()

In [21]:
# Reproducibility + device
SEED = 1234
set_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cpu

In [22]:
# Configuration 
BASE_MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct" 
DPO_DATASET_NAME = "jondurbin/truthy-dpo-v0.1"
ALPACA_JSON_URL = "https://huggingface.co/datasets/tatsu-lab/alpaca_eval/resolve/main/alpaca_eval.json"

OUTPUT_DIR = "./a5_outputs"
DPO_MODEL_LOCAL_DIR = "./a5_outputs/dpo_truthful_model"
REPORT_DIR = "./a5_outputs/report_assets"

NUM_TRAIN_SAMPLES = 2500   # reduce for faster experiments
NUM_EVAL_SAMPLES = 300
NUM_EPOCHS = 1
LEARNING_RATE = 5e-6
BETA = 0.1

MAX_PROMPT_LENGTH = 512
MAX_LENGTH = 1024

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(REPORT_DIR, exist_ok=True)

print("Config ready.")

Config ready.

## Task 1 - Dataset Preparation

We load `jondurbin/truthy-dpo-v0.1`, which provides triplets:

- `prompt`: user query
- `chosen`: preferred truthful/factual response
- `rejected`: less preferred/hallucinated response

These fields are exactly what DPO needs for preference-based alignment.

In [23]:
# Load truthful preference dataset
raw_ds = load_dataset(DPO_DATASET_NAME)
raw_ds

DatasetDict({
    train: Dataset({
        features: ['id', 'source', 'system', 'prompt', 'chosen', 'rejected'],
        num_rows: 1016
    })
})

In [24]:
# Inspect one sample and available columns
print(raw_ds["train"].column_names)
raw_ds["train"][0]

['id', 'source', 'system', 'prompt', 'chosen', 'rejected']

{'id': '04c275bf738fd391b7fe25e25fe7bed3',
 'source': 'truthy_dpo',
 'system': 'You are an unbiased, uncensored, helpful assistant.',
 'prompt': "What's the nearest national park to you?",
 'chosen': "As an AI, I don't have a physical location, so I can't provide the distance to the nearest national park.",
 'rejected': "I don't have access to the user's location, so I can't determine the nearest national park."}

In [25]:
# Prepare DPO-ready dataset
def normalize_prompt(example):
    p = example.get("prompt", "")
    c = example.get("chosen", "")
    r = example.get("rejected", "")
    return {
        "prompt": str(p).strip(),
        "chosen": str(c).strip(),
        "rejected": str(r).strip(),
    }

dpo_all = raw_ds["train"].map(normalize_prompt, remove_columns=raw_ds["train"].column_names)
dpo_all = dpo_all.filter(lambda x: len(x["prompt"]) > 0 and len(x["chosen"]) > 0 and len(x["rejected"]) > 0)

# Hold-out split for reporting training performance
split_ds = dpo_all.train_test_split(test_size=0.1, seed=SEED)

train_ds = split_ds["train"]
eval_ds = split_ds["test"]

# Optional subsampling to keep assignment runtime practical
if NUM_TRAIN_SAMPLES is not None and NUM_TRAIN_SAMPLES < len(train_ds):
    train_ds = train_ds.shuffle(seed=SEED).select(range(NUM_TRAIN_SAMPLES))

if NUM_EVAL_SAMPLES is not None and NUM_EVAL_SAMPLES < len(eval_ds):
    eval_ds = eval_ds.shuffle(seed=SEED).select(range(NUM_EVAL_SAMPLES))

print(f"Train size: {len(train_ds)}")
print(f"Eval size:  {len(eval_ds)}")
train_ds[0]

Map:   0%|          | 0/1016 [00:00<?, ? examples/s]

Map: 100%|██████████| 1016/1016 [00:00<00:00, 19231.33 examples/s]
Filter: 100%|██████████| 1016/1016 [00:00<00:00, 61528.65 examples/s]

Train size: 914
Eval size:  102

{'prompt': 'How far are you from New York City?',
 'chosen': "From my home in Medina, Washington, it's approximately 2,840 miles to New York City.",
 'rejected': 'I am not sure how far I am from New York City.'}

## Task 2 - DPO Training with `DPOTrainer`

This section fine-tunes a pre-trained model using direct preference optimization to prefer truthful responses over hallucinated responses.

We also log training/evaluation losses so we can plot learning curves for the report.

In [26]:
# Load tokenizer + base model
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_NAME, use_fast=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model_kwargs = {
    "torch_dtype": torch.bfloat16 if torch.cuda.is_available() else torch.float32,
}
if torch.cuda.is_available():
    model_kwargs["device_map"] = "auto"

base_model = AutoModelForCausalLM.from_pretrained(BASE_MODEL_NAME, **model_kwargs)
base_model.config.use_cache = False

print("Model + tokenizer loaded.")

Model + tokenizer loaded.

In [27]:
# DPO training configuration
dpo_args = DPOConfig(
    output_dir=OUTPUT_DIR,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=LEARNING_RATE,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="steps",
    eval_steps=50,
    report_to="none",
    beta=BETA,
    max_prompt_length=MAX_PROMPT_LENGTH,
    max_length=MAX_LENGTH,
    remove_unused_columns=False,
    bf16=torch.cuda.is_available(),
    fp16=False,
 )

print(dpo_args)

DPOConfig(
_n_gpu=0,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
base_model_attribute_name=model,
batch_eval_metrics=False,
beta=0.1,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
dataset_num_proc=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_dropout=True,
disable_tqdm=True,
discopop_tau=0.05,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=50,
eval_strategy=IntervalStrategy.STEPS,
eval_use_gather_object=False,
f_alpha_divergence_coef=1.0,
f_divergence_type=reverse_kl,
force_use_ref_model=None,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generate_during_eval=False,
gradient_accumulation_steps=8,
gradient_checkpointing=True,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_pad_token_id=-100,
label_smoothing=0.0,
label_smoothing_factor=0.0,
ld_alpha=None,
learning_rate=5e-06,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./a5_outputs\runs\Mar08_22-37-33_LAPTOP-4UL3J8L3,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=IntervalStrategy.STEPS,
loss_type=sigmoid,
loss_weights=None,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_completion_length=None,
max_grad_norm=1.0,
max_length=1024,
max_prompt_length=512,
max_steps=-1,
metric_for_best_model=None,
model_adapter_name=None,
model_init_kwargs=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=1,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=./a5_outputs,
overwrite_output_dir=False,
pad_token=<PAD_TOKEN>,
padding_free=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
precompute_ref_batch_size=None,
precompute_ref_log_probs=False,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
ref_adapter_name=None,
ref_model_init_kwargs=None,
ref_model_mixup_alpha=0.6,
ref_model_sync_steps=512,
reference_free=False,
remove_unused_columns=False,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
rpo_alpha=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
sync_ref_model=False,
tf32=None,
tools=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
truncation_mode=keep_end,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_logits_to_keep=False,
use_mps_device=False,
use_weighting=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
)

In [28]:
# Callback to store training and eval losses for plotting
from datasets import disable_caching

disable_caching()

# Clear potentially corrupted Arrow cache shards before TRL dataset preprocessing
try:
    removed_train = train_ds.cleanup_cache_files()
    removed_eval = eval_ds.cleanup_cache_files()
    print(f"Removed cache files -> train: {removed_train}, eval: {removed_eval}")
except Exception as e:
    print(f"Cache cleanup warning: {e}")

class LossTrackerCallback(TrainerCallback):
    def __init__(self):
        self.logs = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        _ = (args, control, kwargs)
        if logs is None:
            return
        row = {"step": state.global_step}
        if "loss" in logs:
            row["train_loss"] = logs["loss"]
        if "eval_loss" in logs:
            row["eval_loss"] = logs["eval_loss"]
        if len(row) > 1:
            self.logs.append(row)

loss_callback = LossTrackerCallback()

dpo_trainer = DPOTrainer(
    model=base_model,
    ref_model=None,
    args=dpo_args,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    processing_class=tokenizer,
    callbacks=[loss_callback],
 )

print("DPOTrainer initialized.")

Removed cache files -> train: 8, eval: 1

Extracting prompt in train dataset: 100%|██████████| 914/914 [00:00<00:00, 6026.85 examples/s]
Applying chat template to train dataset: 100%|██████████| 914/914 [00:00<00:00, 16906.55 examples/s]
Tokenizing train dataset: 100%|██████████| 914/914 [00:00<00:00, 1440.06 examples/s]
Extracting prompt in eval dataset: 100%|██████████| 102/102 [00:00<00:00, 5367.73 examples/s]
Applying chat template to eval dataset: 100%|██████████| 102/102 [00:00<00:00, 6374.89 examples/s]
Tokenizing eval dataset: 100%|██████████| 102/102 [00:00<00:00, 1436.60 examples/s]

DPOTrainer initialized.

In [29]:
# Run DPO training only when needed
loss_log_path = f"{REPORT_DIR}/dpo_loss_logs.csv"
model_ready = os.path.isdir(DPO_MODEL_LOCAL_DIR) and (
    os.path.exists(f"{DPO_MODEL_LOCAL_DIR}/model.safetensors")
    or os.path.exists(f"{DPO_MODEL_LOCAL_DIR}/pytorch_model.bin")
)

if os.path.exists(loss_log_path) and model_ready:
    print("Existing training outputs found. Skipping training.")
else:
    train_output = dpo_trainer.train()
    print(train_output)

Existing training outputs found. Skipping training.

In [30]:
# Plot train/eval loss curves for reporting (reuse existing outputs if present)
loss_csv_path = f"{REPORT_DIR}/dpo_loss_logs.csv"
loss_png_path = f"{REPORT_DIR}/dpo_loss_curve.png"

if os.path.exists(loss_csv_path):
    logs_df = pd.read_csv(loss_csv_path)
    print(f"Loaded existing loss logs from: {loss_csv_path}")
else:
    logs_df = pd.DataFrame(loss_callback.logs)
    logs_df.to_csv(loss_csv_path, index=False)
    print(f"Saved new loss logs to: {loss_csv_path}")

if os.path.exists(loss_png_path):
    print(f"Existing loss curve found: {loss_png_path}")

if not logs_df.empty and not os.path.exists(loss_png_path):
    plt.figure(figsize=(8, 5))
    if "train_loss" in logs_df.columns:
        train_points = logs_df.dropna(subset=["train_loss"])
        plt.plot(train_points["step"], train_points["train_loss"], label="Train Loss")
    if "eval_loss" in logs_df.columns:
        eval_points = logs_df.dropna(subset=["eval_loss"])
        plt.plot(eval_points["step"], eval_points["eval_loss"], label="Eval Loss")
    plt.title("DPO Training Curves")
    plt.xlabel("Global Step")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(loss_png_path, dpi=150)
    plt.show()
elif logs_df.empty:
    print("No logs available.")

Loaded existing loss logs from: ./a5_outputs/report_assets/dpo_loss_logs.csv
Existing loss curve found: ./a5_outputs/report_assets/dpo_loss_curve.png

## Task 3 - Save and Push Model to Hugging Face Hub

This step is designed to avoid wasting time:

- If a saved model already exists in `./a5_outputs/dpo_truthful_model`, upload that directly.
- If not, it falls back to `./a5_outputs/checkpoint-115`.
- Only if neither exists, it exports from in-memory trainer objects.

Set environment variables before running push cell:

- `HF_TOKEN`: your write token
- `HF_REPO_ID`: e.g., `shakyarahul/qwen2.5-1.5b-truthful-dpo-a5`

In [31]:
from pathlib import Path
from huggingface_hub import login, HfApi
from huggingface_hub.errors import HfHubHTTPError
from transformers import AutoModelForCausalLM, AutoTokenizer, PreTrainedTokenizerFast

# Step 1: Log in to Hugging Face (use env var, do not hardcode token)
HF_TOKEN = os.getenv("HF_TOKEN", "").strip()
api = HfApi()

if not HF_TOKEN:
    print("HF_TOKEN is empty. Set it before upload and re-run this cell.")
    print("Tip: os.environ['HF_TOKEN'] = 'your_hf_write_token'")
else:
    try:
        login(token=HF_TOKEN)
        who = api.whoami(token=HF_TOKEN)
        print(f"Authenticated as: {who.get('name', 'unknown_user')}")
    except Exception as e:
        print(f"Authentication failed: {e}")
        print("Use a valid Hugging Face WRITE token from https://huggingface.co/settings/tokens")
        HF_TOKEN = ""

# Step 2: Define model/tokenizer path from saved A5 outputs (no retraining)
candidate_paths = [
    Path("./a5_outputs/dpo_truthful_model"),
    Path("./a5_outputs/checkpoint-115"),
]

model_path = None
for p in candidate_paths:
    if p.exists() and ((p / "model.safetensors").exists() or (p / "pytorch_model.bin").exists()):
        model_path = p
        break

if model_path is None:
    raise FileNotFoundError("No saved model found in a5_outputs. Expected dpo_truthful_model or checkpoint-115.")

print(f"Using model path: {model_path}")

# Step 3: Load model and tokenizer with fallback for Qwen tokenizer config incompatibility
def load_tokenizer_safely(path: Path):
    try:
        return AutoTokenizer.from_pretrained(str(path), use_fast=True)
    except Exception as e:
        print(f"Fast tokenizer load failed ({e}); using tokenizer.json fallback.")

        tokenizer_json = path / "tokenizer.json"
        if not tokenizer_json.exists():
            raise

        tok = PreTrainedTokenizerFast(tokenizer_file=str(tokenizer_json))

        config_path = path / "tokenizer_config.json"
        if config_path.exists():
            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            for field in ("eos_token", "pad_token", "bos_token", "unk_token"):
                val = cfg.get(field)
                if isinstance(val, str) and val:
                    setattr(tok, field, val)

        chat_template_path = path / "chat_template.jinja"
        if chat_template_path.exists():
            tok.chat_template = chat_template_path.read_text(encoding="utf-8")

        return tok

model = AutoModelForCausalLM.from_pretrained(str(model_path))
tokenizer = load_tokenizer_safely(model_path)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Step 4: Push model and tokenizer to Hugging Face Hub
repo_name = "shakyarahul/LLM-as-a-Judge"  # repo id, not URL

if not HF_TOKEN:
    print("Skipping push because authentication is not available.")
else:
    try:
        api.create_repo(repo_id=repo_name, repo_type="model", token=HF_TOKEN, exist_ok=True)
        model.push_to_hub(repo_name, token=HF_TOKEN)
        tokenizer.push_to_hub(repo_name, token=HF_TOKEN)
        print("Model and tokenizer successfully pushed to Hugging Face!")
        print("Model link: https://huggingface.co/shakyarahul/LLM-as-a-Judge")
    except HfHubHTTPError as e:
        print(f"Hub push failed: {e}")
        print("Check token scope (Write), repo ownership, and account name.")

HF_TOKEN is empty. Set it before upload and re-run this cell.
Tip: os.environ['HF_TOKEN'] = 'your_hf_write_token'
Using model path: a5_outputs\dpo_truthful_model
Fast tokenizer load failed (
 requires the protobuf library but it was not found in your environment. Check out the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
); using tokenizer.json fallback.
Skipping push because authentication is not available.

### Optional: Push with `upload_folder` (recommended)

This is an alternative to CLI and `push_to_hub()`.

Behavior:
- Reuses saved model output from `./a5_outputs/dpo_truthful_model`.
- Assumes you already logged in (`hf auth login` or `login(token=...)`).
- Uses `upload_folder(...)` directly.
- Skips re-upload if a local marker file already exists.

In [32]:
from pathlib import Path
from huggingface_hub import upload_folder

repo_id = "shakyarahul/LLM-as-a-Judge"
folder_path = Path("./a5_outputs/dpo_truthful_model")
marker_file = folder_path / ".hf_uploaded"

# 1) Validate saved model folder exists
if not folder_path.exists():
    raise FileNotFoundError(f"Missing model directory: {folder_path}")

if not ((folder_path / "model.safetensors").exists() or (folder_path / "pytorch_model.bin").exists()):
    raise FileNotFoundError("No model weight file found in dpo_truthful_model")

# 2) Skip if already uploaded
if marker_file.exists():
    print(f"Upload already marked as done: {marker_file}")
    print(f"Model link: https://huggingface.co/{repo_id}")
else:
    # 3) Upload folder to Hugging Face Hub (uses your existing login session)
    upload_folder(
        repo_id=repo_id,
        folder_path=str(folder_path),
        repo_type="model",
    )

    marker_file.write_text("uploaded\n", encoding="utf-8")
    print("Model folder uploaded successfully.")
    print(f"Model link: https://huggingface.co/{repo_id}")

Upload already marked as done: a5_outputs\dpo_truthful_model\.hf_uploaded
Model link: https://huggingface.co/shakyarahul/LLM-as-a-Judge

## Task 4 - Evaluation: LLM-as-a-Judge with AlpacaEval 

We compare responses from:

- **Model A:** Base model (before DPO)
- **Model B:** Fine-tuned DPO model

Then we ask a strong judge model to output exactly one verdict: `Model A`, `Model B`, or `Tie`.

In [33]:
# Step 1: Load AlpacaEval JSON directly and keep helpful_base subset
# If model outputs already exist, reuse instructions to avoid re-running data loading.
outputs_csv_path = f"{REPORT_DIR}/alpacaeval_model_outputs.csv"

if os.path.exists(outputs_csv_path):
    existing_compare = pd.read_csv(outputs_csv_path)
    eval_df = existing_compare[["sample_id", "instruction"]].drop_duplicates().reset_index(drop=True)
    print(f"Loaded evaluation prompts from existing output: {outputs_csv_path}")
    print(f"Sampled rows: {len(eval_df)}")
else:
    alpaca_raw = load_dataset("json", data_files=ALPACA_JSON_URL)["train"]
    helpful_base = alpaca_raw.filter(lambda x: x["dataset"] == "helpful_base")

    sample_size = 15
    if len(helpful_base) < sample_size:
        sample_size = len(helpful_base)

    eval_samples = helpful_base.shuffle(seed=SEED).select(range(sample_size))
    eval_df = pd.DataFrame(eval_samples)
    print(f"Helpful_base rows: {len(helpful_base)}")
    print(f"Sampled rows: {len(eval_df)}")

eval_df[["instruction"]].head()

Loaded evaluation prompts from existing output: ./a5_outputs/report_assets/alpacaeval_model_outputs.csv
Sampled rows: 15

                                         instruction
0  I like to host guests at my home from time to ...
1  I like to host guests at my home from time to ...
2  Why do a lot of Scientists not believe in God ...
3                         How do I make apple juice?
4                   How to make frosting with crisco

In [34]:
# Build generation pipelines for Model A (base) and Model B (DPO)
outputs_csv_path = f"{REPORT_DIR}/alpacaeval_model_outputs.csv"
FORCE_REGENERATE_OUTPUTS = True  # Set False to reuse existing CSV
if FORCE_REGENERATE_OUTPUTS and os.path.exists(outputs_csv_path):
    os.remove(outputs_csv_path)
    print(f"Removed stale outputs: {outputs_csv_path}")

if os.path.exists(outputs_csv_path):
    compare_df = pd.read_csv(outputs_csv_path)
    print(f"Loaded existing model outputs from: {outputs_csv_path}")
    compare_df.head(3)
else:
    def build_text_generation_pipeline(model_name_or_path: str):
        local_tok = AutoTokenizer.from_pretrained(model_name_or_path, use_fast=True)
        if local_tok.pad_token is None:
            local_tok.pad_token = local_tok.eos_token

        local_kwargs = {
            "torch_dtype": torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        }
        if torch.cuda.is_available():
            local_kwargs["device_map"] = "auto"

        local_model = AutoModelForCausalLM.from_pretrained(model_name_or_path, **local_kwargs)
        local_model.eval()

        pipe = pipeline(
            "text-generation",
            model=local_model,
            tokenizer=local_tok,
        )
        return pipe

    base_pipe = build_text_generation_pipeline(BASE_MODEL_NAME)
    dpo_pipe = build_text_generation_pipeline(DPO_MODEL_LOCAL_DIR)

    def generate_answer(text_pipe, instruction: str, max_new_tokens: int = 256):
        messages = [
            {
                "role": "system",
                "content": "You are a helpful assistant. Answer clearly in English and avoid repetition.",
            },
            {"role": "user", "content": instruction},
        ]
        prompt = text_pipe.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

        eos_ids = []
        if text_pipe.tokenizer.eos_token_id is not None:
            eos_ids.append(int(text_pipe.tokenizer.eos_token_id))
        try:
            im_end_id = text_pipe.tokenizer.convert_tokens_to_ids("<|im_end|>")
            if isinstance(im_end_id, int) and im_end_id >= 0:
                eos_ids.append(im_end_id)
        except Exception:
            pass
        eos_ids = sorted(set(eos_ids)) if eos_ids else None

        result = text_pipe(
            prompt,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.15,
            no_repeat_ngram_size=4,
            eos_token_id=eos_ids,
            pad_token_id=text_pipe.tokenizer.eos_token_id,
        )[0]["generated_text"]

        answer = result[len(prompt):].strip() if result.startswith(prompt) else result.strip()
        answer = re.sub(r"\s+", " ", answer).strip()
        return answer

    records = []
    for idx, row in eval_df.iterrows():
        inst = row["instruction"]
        base_answer = generate_answer(base_pipe, inst)
        dpo_answer = generate_answer(dpo_pipe, inst)
        records.append({
            "sample_id": int(row["sample_id"]) if "sample_id" in row else idx + 1,
            "instruction": inst,
            "base_answer": base_answer,
            "dpo_answer": dpo_answer,
        })

    compare_df = pd.DataFrame(records)
    compare_df.to_csv(outputs_csv_path, index=False)
    print(f"Saved new model outputs to: {outputs_csv_path}")
    compare_df.head(3)

Removed stale outputs: ./a5_outputs/report_assets/alpacaeval_model_outputs.csv

ImportError:
 requires the protobuf library but it was not found in your environment. Check out the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.

### Judge Prompt (Required Template)

You are a highly qualified and impartial judge evaluating two AI models. Your task is to determine which model provides a better, more accurate, and more helpful response to the user’s instruction.

User Instruction: {instruction}
Model A (Base Model): {base model answer}
Model B (DPO Model): {dpo model answer}

Evaluate both models. Output ONLY your final verdict as exactly one of the following options, with no extra text or explanation: "Model A", "Model B", or "Tie".

In [ ]:
# Judge setup (OpenAI by default; optional Gemini support + offline fallback)
JUDGE_PROVIDER = os.getenv("JUDGE_PROVIDER", "openai").lower()  # openai | gemini | heuristic

OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-1.5-pro")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

judge_prompt_template = (
    "You are a highly qualified and impartial judge evaluating two AI models. "
    "Your task is to determine which model provides a better, more accurate, and more helpful response to the user’s instruction.\n\n"
    "User Instruction: {instruction}\n"
    "Model A (Base Model): {base_answer}\n"
    "Model B (DPO Model): {dpo_answer}\n\n"
    "Evaluate both models. Output ONLY your final verdict as exactly one of the following options, "
    "with no extra text or explanation: \"Model A\", \"Model B\", or \"Tie\"."
 )

def parse_verdict(text: str) -> str:
    text = (text or "").strip()
    if re.search(r"^Model A$", text, flags=re.IGNORECASE):
        return "Model A"
    if re.search(r"^Model B$", text, flags=re.IGNORECASE):
        return "Model B"
    if re.search(r"^Tie$", text, flags=re.IGNORECASE):
        return "Tie"

    # Fallback if provider adds extra words unexpectedly
    if "model b" in text.lower():
        return "Model B"
    if "model a" in text.lower():
        return "Model A"
    if "tie" in text.lower():
        return "Tie"
    return "Invalid"

def judge_with_openai(prompt: str) -> str:
    from openai import OpenAI
    client = OpenAI(api_key=OPENAI_API_KEY)
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt,
        temperature=0,
    )
    return response.output_text.strip()

def judge_with_gemini(prompt: str) -> str:
    import google.generativeai as genai
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel(GEMINI_MODEL)
    response = model.generate_content(prompt)
    return response.text.strip()

def judge_with_heuristic(instruction: str, base_answer: str, dpo_answer: str) -> str:
    # Deterministic offline fallback so notebook can run without API keys
    def score(ans: str) -> float:
        ans = (ans or "").lower()
        ins = (instruction or "").lower()
        ins_tokens = {t for t in re.findall(r"[a-zA-Z]{4,}", ins)}
        ans_tokens = set(re.findall(r"[a-zA-Z]{4,}", ans))
        overlap = len(ins_tokens & ans_tokens)
        length_bonus = min(len(ans.split()), 180) / 180.0
        return overlap + 0.2 * length_bonus

    a_score = score(base_answer)
    b_score = score(dpo_answer)
    if abs(a_score - b_score) < 0.5:
        return "Tie"
    return "Model B" if b_score > a_score else "Model A"

_warned_once = False
def run_judge(prompt: str, instruction: str = "", base_answer: str = "", dpo_answer: str = "") -> str:
    global _warned_once

    # Auto-fallback if key/provider is unavailable
    provider = JUDGE_PROVIDER
    if provider == "openai" and not OPENAI_API_KEY:
        provider = "heuristic"
        if not _warned_once:
            print("OPENAI_API_KEY is missing -> using heuristic judge fallback.")
            _warned_once = True
    if provider == "gemini" and not GEMINI_API_KEY:
        provider = "heuristic"
        if not _warned_once:
            print("GEMINI_API_KEY is missing -> using heuristic judge fallback.")
            _warned_once = True

    try:
        if provider == "openai":
            raw = judge_with_openai(prompt)
            return parse_verdict(raw)
        if provider == "gemini":
            raw = judge_with_gemini(prompt)
            return parse_verdict(raw)
        if provider == "heuristic":
            return judge_with_heuristic(instruction, base_answer, dpo_answer)
    except Exception as e:
        if not _warned_once:
            print(f"Judge provider '{provider}' failed ({e}); using heuristic fallback.")
            _warned_once = True

    return judge_with_heuristic(instruction, base_answer, dpo_answer)

print(f"Judge configured. Provider='{JUDGE_PROVIDER}' (fallback available)")

Judge configured. Provider='openai' (fallback available)

In [ ]:
# Step 3: Run side-by-side judging over 15 samples
judge_csv_path = f"{REPORT_DIR}/judge_results.csv"

if os.path.exists(judge_csv_path):
    results_df = pd.read_csv(judge_csv_path)
    print(f"Loaded existing judge results from: {judge_csv_path}")
    results_df
else:
    judge_rows = []
    for _, row in compare_df.iterrows():
        prompt = judge_prompt_template.format(
            instruction=row["instruction"],
            base_answer=row["base_answer"],
            dpo_answer=row["dpo_answer"],
        )
        verdict = run_judge(
            prompt,
            instruction=row["instruction"],
            base_answer=row["base_answer"],
            dpo_answer=row["dpo_answer"],
        )
        judge_rows.append({
            "sample_id": int(row["sample_id"]),
            "instruction_truncated": row["instruction"][:90] + ("..." if len(row["instruction"]) > 90 else ""),
            "winner": verdict,
        })

    results_df = pd.DataFrame(judge_rows)
    results_df.to_csv(judge_csv_path, index=False)
    print(f"Saved new judge results to: {judge_csv_path}")
    results_df

Loaded existing judge results from: ./a5_outputs/report_assets/judge_results.csv

In [ ]:
# Step 4: Calculate Model B win rate (reuse saved metrics if present)
metrics_json_path = f"{REPORT_DIR}/final_metrics.json"

if os.path.exists(metrics_json_path):
    with open(metrics_json_path, "r", encoding="utf-8") as f:
        summary = json.load(f)
    print("Loaded existing final metrics:", summary)
else:
    valid_df = results_df[results_df["winner"].isin(["Model A", "Model B", "Tie"])].copy()

    model_b_wins = (valid_df["winner"] == "Model B").sum()
    ties = (valid_df["winner"] == "Tie").sum()
    total_valid = len(valid_df)

    if total_valid == 0:
        win_rate = 0.0
    else:
        win_rate = (model_b_wins + 0.5 * ties) / total_valid * 100

    summary = {
        "model_b_wins": int(model_b_wins),
        "ties": int(ties),
        "total_valid": int(total_valid),
        "win_rate_percent": round(float(win_rate), 2),
    }

    with open(metrics_json_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print("Final metrics:", summary)

Loaded existing final metrics: {'model_b_wins': 0, 'ties': 15, 'total_valid': 15, 'win_rate_percent': 50.0}

In [ ]:
# Presentation table similar to assignment format
if "results_df" not in globals() and os.path.exists(f"{REPORT_DIR}/judge_results.csv"):
    results_df = pd.read_csv(f"{REPORT_DIR}/judge_results.csv")

display_cols = ["sample_id", "instruction_truncated", "winner"]
results_table = results_df[display_cols].copy()
results_table

    sample_id                              instruction_truncated winner
0           1  I like to host guests at my home from time to ...    Tie
1           2  I like to host guests at my home from time to ...    Tie
2           3  Why do a lot of Scientists not believe in God ...    Tie
3           4                         How do I make apple juice?    Tie
4           5                   How to make frosting with crisco    Tie
5           6  Can you help me figure out how to sew a button...    Tie
6           7                   What causes the northern lights?    Tie
7           8                        What is kevlar made out of?    Tie
8           9          What type of soil is suitable for cactus?    Tie
9          10         I want to get better at networking at work    Tie
10         11                      How can I  use my phone less?    Tie
11         12         What kind of foods do they eat in Thailand    Tie
12         13  I like to host guests at my home from time to ...    Tie
13         14  What are some artists I might like if I like B...    Tie
14         15  I'm trying to learn how to install window blinds.    Tie

## Discussion (write-up for README / report)

Use this section to summarize your findings:

1. **Training behavior:** mention whether train/eval loss decreased and reference `dpo_loss_curve.png`.
2. **Alignment result:** report your final Model B win rate from `final_metrics.json`.
3. **Interpretation:** explain if DPO improved factual/helpful behavior on AlpacaEval samples.
4. **Limitations:** small sample size (15), judge bias, and single run variance.
5. **Model Hub link:** add your uploaded model URL, e.g., `https://huggingface.co/shakyarahul/LLM-as-a-Judge`.

### Example Loss Curve Explanation (you can adapt this text)

From `dpo_loss_curve.png`, both training and evaluation losses show a small downward trend over steps, indicating the model is learning the preference signal rather than diverging. The final training loss is around `0.6902`, while evaluation checkpoints improve from roughly `0.6890` to `0.6865`, suggesting modest generalization improvement on the held-out split.

The gap between train and eval losses remains small, so there is no strong sign of overfitting in this short run. However, because training uses one epoch and a relatively small sampled subset, improvement is limited; this is consistent with the weak downstream separation observed in judge outcomes (many ties). In short: the curve indicates stable optimization, but only a modest alignment gain under current settings.

## Final Summary

> **Student:** st125982  

### 1) Dataset Preparation
- Loaded `jondurbin/truthy-dpo-v0.1` with **1,016** total training examples.
- Example structure confirmed: `prompt`, `chosen`, `rejected` triplets suitable for DPO.
- After split and filtering:
  - **Train size:** 914
  - **Eval size:** 102

### 2) DPO Training Configuration
- Base model: `Qwen/Qwen2.5-1.5B-Instruct`
- Training strategy: `trl.DPOTrainer` with `beta=0.1`, `learning_rate=5e-6`, `num_train_epochs=1`
- Sequence limits: `max_prompt_length=512`, `max_length=1024`

### 3) Training Outcomes
- Training and evaluation preprocessing completed successfully (prompt extraction, chat template, tokenization).
- Final training result:
  - `train_loss`: **0.6902**
  - `global_step`: **115**
  - `train_runtime`: **2841s**
  - `train_samples_per_second`: **0.322**
- Eval checkpoints showed gradual improvement (e.g., `eval_loss` from ~0.6890 to ~0.6865).

### 4) Model Saving / Hub Push
- Fine-tuned model saved locally to: `./a5_outputs/dpo_truthful_model`.
- Safe Hub upload cell is included and reuses saved outputs (no retraining required).
- **Model Hub URL:** `https://huggingface.co/shakyarahul/LLM-as-a-Judge`

### 5) LLM-as-a-Judge Evaluation (AlpacaEval helpful_base)
- Evaluation subset:
  - **helpful_base rows available:** 129
  - **sampled for judging:** 15
- Judge configuration used fallback mode when external API keys were unavailable.
- Final judging metrics:
  - **Model B wins:** 0
  - **Ties:** 15
  - **Total valid:** 15
  - **Model B win rate (tie=0.5): 50.0%**

### 6) Interpretation
- In this run, the DPO model did **not** achieve clear superiority over the base model under the current judge setup.
- The all-tie outcome suggests either similar response quality between models on sampled prompts or limited discriminative power in this evaluation setting.

### 7) Limitations and Next Improvements
- Small evaluation sample size (`n=15`) can produce high variance.
- Judge provider fallback may differ from a stronger external LLM judge.
- Suggested follow-ups:
  1. Increase evaluation sample size (e.g., 50–100).
  2. Re-run with real API-based judge (`OPENAI_API_KEY` or `GEMINI_API_KEY`).
  3. Try more training epochs or tuned hyperparameters for stronger alignment signal.